[0m01:23:33.796867 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020158782380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002015ACA9F90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002015ACAA170>]}


============================== 01:23:33.800869 | c5b5a2ba-929b-4e21-a133-1392467649e7 ==============================
[0m01:23:33.800869 [info ] [MainThread]: Running with dbt=1.6.6
[0m01:23:33.801868 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Personal Git Repos\\getground_dbt\\', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt deps', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m01:23:33.802836 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Personal Git Repos\getground_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m01:23:33.804837 [debug] [MainThread]: Command `dbt deps` failed at 01:23:33.804837 after 0.03 seconds
[0m01:23:33.805837 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020158782380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002015ACA9F30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002015ACA91E0>]}
[0m01:23:33.806837 [debug] [MainThread]: Flushing usage events
[0m01:45:58.458177 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228EB702440>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228EDC2A200>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228EDC2A3E0>]}


============================== 01:45:58.458177 | cabccf01-7f93-4693-ad6e-2de7346a092d ==============================
[0m01:45:58.458177 [info ] [MainThread]: Running with dbt=1.6.6
[0m01:45:58.458177 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Personal Git Repos\\getground_dbt\\', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt build --target dev', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m01:45:58.473808 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Personal Git Repos\getground_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m01:45:58.473808 [debug] [MainThread]: Command `dbt build` failed at 01:45:58.473808 after 0.02 seconds
[0m01:45:58.473808 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228EB702440>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228EDC2A3E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228EDC2A140>]}
[0m01:45:58.473808 [debug] [MainThread]: Flushing usage events
[0m01:54:25.753266 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F535302500>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F5376F6F50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F5376F7BE0>]}


============================== 01:54:25.753266 | 5ec4597a-2f05-4dc6-9ca2-ad8f5479e58b ==============================
[0m01:54:25.753266 [info ] [MainThread]: Running with dbt=1.6.6
[0m01:54:25.753266 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Personal Git Repos\\getground_dbt\\', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': "dbt show --inline with a as (\n\n    select * from {{ref('PARTNER_CONSULTANT__EXPECTED'}}\n\n),\n\nb as (\n\n    select * from {{ref('PARTNER_CONSULTANT'}}\n\n),\n\na_minus_b as (\n\n    select PARTNER_ID, CONSULTANT_ID from a\n    \n\n    except\n\n\n    select PARTNER_ID, CONSULTANT_ID from b\n\n),\n\nb_minus_a as (\n\n    select PARTNER_ID, CONSULTANT_ID from b\n    \n\n    except\n\n\n    select PARTNER_ID, CONSULTANT_ID from a\n\n),\n\nunioned as (\n\n    select 'a_minus_b' as which_diff, a_minus_b.* from a_minus_b\n    union all\n    select 'b_minus_a' as which_diff, b_minus_a.* from b_minus_a\n\n)\n\nselect * from unioned\n\n", 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m01:54:25.753266 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Personal Git Repos\getground_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m01:54:25.753266 [debug] [MainThread]: Command `dbt show` failed at 01:54:25.753266 after 0.03 seconds
[0m01:54:25.753266 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F535302500>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F531382530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F5376F6EF0>]}
[0m01:54:25.753266 [debug] [MainThread]: Flushing usage events
